#!/bin/zsh
# Swift Dialog Shell Script Library

main() {
  #dialogTest1
  #dialogTest2
  #dialogTest3
  #alertTest1
  #textFieldAssess "$(testTextField1)"
  testButtons
  exit 0
}

testButtons() {

}

# alpha means transarency
# --help
# --title
# --subtitle
# --message
# --style mini | centered | alert | caution | warning
# --messagealignment [left | centre | center | right]
# --messageposition [top | centre | center | bottom]
# --helpmessage
# --icon
# --iconsize
# --iconalpha
# --overlayicon
# --bannerimage
# --bannertitle
# --bannertext
# --button1text
# --button1action
# --buton2text
# --button2action
# --infobuttontext
# --infobuttonaction
# --buttonstyle
# --selecttitle
# --selectvalues
# --selectdefault
# --titlefont
# --messagefont
# --textfield
# --checkbox
# --checkboxstyle
# --timer
# --progress
# --progresstext
# --image
# --imagecaption
# --width
# --height
# --background
# --bgalpha
# --bgposition
# --bgfill [fill | fit]
# --bgscale [fill | fit]
# --position [topleft | left | bottomleft | top | center/centre | bottom | topright | right | bottomright]
# --positionoffset
# --video
# --videocaption
# --jsonfile
# --jsonstring
# --commandfile
# --listitem
# --liststyle
# --infotext
# --infobox
# --quitkey
# --webcontent
# --key
# --checksum
# --displaylog
# --button1disabled
# --buton2disabled
# --buton2
# --infobutton
# --version
# --hideicon
# --centreicon
# --license
# --hidetimer
# --hidetimerbar
# --autoplay
# --blurscreen
# --notification
# --moveable
# --ontop
# --small
# --big
# --fullscreen
# --quitoninfo
# --json
# --jh
# --mini
# --windbuttons
# --hidedefaultkeyboardaction

dialogTest1() {
  dialog \
    -t "Style: Mini" \
    -m "Alignment has no bearing on mini style" \
    --style mini \
    --messagealignment right \
    --messageposition left
}

dialogTest2() {
  dialog \
    -t "Style: Centered" \
    -m "Position has no bearing on centered style" \
    --style centered \
    --messagealignment center \
    --messageposition center
}

dialogTest3() {
  dialog \
    -t "Style: Right" \
    -m "Alignment & Position: Right" \
    --style right \
    --messagealignment right
}

alertTest1() {
  dialog \
    -t "Style: Alert" \
    -m "Message goes here" \
    --style right \
    --messagealignment right \
    --messageposition right
}

textFieldAssess() {
  readonly delim=" : "
  readonly first_three="$(cut -c -3 <<< $@)"
  readonly text_field="$(cut -c 4- <<< $@)"
  [ "$first_three" = "$delim" ] && echo "$text_field" || echo error
}

testTextField1() {
  dialog \
    --textfield ,secure \
    --title "Text Field" \
    --message "Enter a secure test password: " \
    --subtitle "Security Test" \
    --icon "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
}

[ "$ZSH_EVAL_CONTEXT" = "toplevel" ] && main